# Generated by Django 5.1.5 on 2025-02-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
